// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQakYY4oCS9o63OXF2IukJvXFOGLaIObM',
    appId: '1:115351544737:web:2450c3bc88eebe1c2961e0',
    messagingSenderId: '115351544737',
    projectId: 'carelink-57d19',
    authDomain: 'carelink-57d19.firebaseapp.com',
    storageBucket: 'carelink-57d19.firebasestorage.app',
    measurementId: 'G-HRN365QCYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuBjaHPDcBB-O1v3Vh_D0pDe_znK8kS38',
    appId: '1:115351544737:android:d4a76fda80ace2a92961e0',
    messagingSenderId: '115351544737',
    projectId: 'carelink-57d19',
    storageBucket: 'carelink-57d19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GPdQ3h7UsB2k7HoAwwoLy82sqld8GrA',
    appId: '1:115351544737:ios:257eab90c2ad8c1d2961e0',
    messagingSenderId: '115351544737',
    projectId: 'carelink-57d19',
    storageBucket: 'carelink-57d19.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6GPdQ3h7UsB2k7HoAwwoLy82sqld8GrA',
    appId: '1:115351544737:ios:257eab90c2ad8c1d2961e0',
    messagingSenderId: '115351544737',
    projectId: 'carelink-57d19',
    storageBucket: 'carelink-57d19.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQakYY4oCS9o63OXF2IukJvXFOGLaIObM',
    appId: '1:115351544737:web:900260f16055204d2961e0',
    messagingSenderId: '115351544737',
    projectId: 'carelink-57d19',
    authDomain: 'carelink-57d19.firebaseapp.com',
    storageBucket: 'carelink-57d19.firebasestorage.app',
    measurementId: 'G-6WRTD5H0RR',
  );
}
